<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f7277d4d-042a-419c-aaaa-0a9b34d5f3cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bStartPB  : BOOL;
	bEndPB :	BOOL	;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>